<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.Bot" Version="19.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\Infrastructure.Domain\Infrastructure.Domain.csproj" />
  </ItemGroup>


</Project>