<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Avalonia" Version="8.1.97.11073" />
    <PackageReference Include="Material.Avalonia" Version="3.12.0" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Common\Common.Core\Common.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Language.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Language.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Properties\Language.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Language.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>