<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Common\Common.Ui\Common.Ui.csproj" />
      <ProjectReference Include="..\Confirmation.Domain\Confirmation.Domain.csproj" />
      <ProjectReference Include="..\Confirmation.Ui\Confirmation.Ui.csproj" />
    </ItemGroup>

</Project>
