<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.10.9" />
    <PackageReference Include="Prism.Avalonia" Version="8.1.97.11073" />
    <PackageReference Include="Material.Avalonia" Version="3.6.0" />
    <PackageReference Include="Material.Avalonia.DataGrid" Version="3.6.0" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.10" />
    <PackageReference Include="ReactiveUI" Version="18.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Ui\Common.Ui.csproj" />
    <ProjectReference Include="..\..\DataBase\FilmesDB.Domain\FilmsDB.Domain.csproj" />
    <ProjectReference Include="..\Game.Infrastructure.Interfaces\Game.Infrastructure.Interfaces.csproj" />
  </ItemGroup>

</Project>